export const BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8080";
export const API_ROUTES = {

  ADMIN: {
    LOGIN: "/api/admin/login",
    FETCH_USERS: "/api/admin/users",
    BLOCK_USERS: (id: string) => `/api/admin/users/${id}/block`,
    UNBLOCK_USERS: (id: string) => `/api/admin/users/${id}/unblock`,
    FETCH_LAWYERS: '/api/admin/lawyers',
    BLOCK_LAWYER: (id: string) => `/api/admin/lawyers/${id}/block`,
    UNBLOCK_LAWYER: (id: string) => `/api/admin/lawyers/${id}/unblock`,
    APPROVE_LAWYER: (id: string) => `/api/admin/lawyers/${id}/approve`,
    REJECT_LAWYER: (id: string) => `/api/admin/lawyers/${id}/reject`,
    CREATESUBSCRIPTION: '/api/admin/subscription/create',
    FETCH_SUBSCRIPTIONS: '/api/admin/subscription',
    LOGOUT_ADMIN: '/api/admin/logout',
    PAYMENTS: '/api/admin/payments',
    PAYOUT_PENDING: '/api/admin/payout/pending',
    APPROVE_PAYOUT: (id: string) => `/api/admin/payout/${id}/approve`,
    DASHBOARD_STATS: "/api/admin/dashboard/stats",
    BOOKINGS: `/api/admin/bookings`,
    SPECIALIZATIONS: '/api/admin/specialization',
    SPECIALIZATION: (id: string) => `/api/admin/specialization/${id}`
  },

  USER: {
    LOGIN: "/api/user/login",
    REGISTER: "/api/user/register",
    VERIFY_OTP: "/api/user/verify-otp",
    RESEND_OTP: "/api/user/resend-otp",
    GOOGLE_AUTH: "/api/user/google",
    FORGOT_PASSWORD: "/api/user/forget-password",
    RESET_PASSWORD: "/api/user/reset-password",
    LOGOUT_USER: `/api/user/logout`,
    GETPROFILE: `/api/user/profile`,
    UPDATE_PROFILE_INFO: "/api/user/profile/update",
    CHANGE_PASSWORD: "/api/user/profile/password",
    GETALL_LAWYERS: '/api/user/lawyers',
    SINGLE_LAWYER: (id: string) => `/api/user/lawyers/${id}`,
    GETSLOTS: (id: string) => `/api/user/lawyers/slots/${id}`,
    ADDREVIEW: '/api/user/review',
    GETALLREVIEWS: (id: string) => `/api/user/review/${id}`,
    CANCELAPPOINMENT: (id: string) => `/api/booking/appointments/${id}/cancel`,
    CANCEL_FOLLOW_UP: (id: string) => `/api/booking/appointments/${id}/cancel-follow-up`,
    RESCHEDULE_APPOINTMENT: (id: string) => `/api/booking/appointments/${id}/reschedule`,
    GETAPPOINMENT: '/api/booking/appointments',
    SPECIALIZATIONS: '/api/user/specializations',
    GETWALLET: `/api/user/wallet`,
    REFRESH_TOKEN_URL: "/api/user/refresh"
  },

  PAYMENT: {
    PAYMENT: `/api/booking/create-checkout-session`,
    CONFIRM: `/api/booking/confirm`,
    WALLET_BOOKING: `/api/booking/wallet-booking`
  },

  LAWYER: {
    REGISTER: "/api/user/register",
    VERIFY_DETAILS: "/api/lawyer/verifyDetils",
    LOGOUT_LAWYER: `/api/lawyer/logout`,
    SCHEDULE_CREATE: '/api/lawyer/schedule/create',
    SCHEDULE_UPDATE: `/api/lawyer/schedule/update`,
    FETCH_SCHEDULT_RULE: `/api/lawyer/schedule`,
    DELETE_SCHEDULE_RULE: '/api/lawyer/schedule/delete',
    GETPROFILE: `/api/lawyer/profile`,
    UPDATE_PROFILE: `/api/lawyer/profile/update`,
    CHANGE_PASSWORD: "/api/lawyer/profile/password",
    APPOIMENTS: `/api/lawyer/appoiments`,
    APPOIMENTS_UPDATE_STATUS: (id: string) => `/api/lawyer/appoiments/${id}/status`,
    APPOIMENTS_FOLLOW_UP: (id: string) => `/api/lawyer/appoiments/${id}/follow-up`,
    APPOIMENTS_RESCHEDULE: (id: string) => `/api/lawyer/appoiments/${id}/reschedule`,

    CHECKSUBSCRIPTION: `/api/lawyer/checksubscription`,
    CURRENT_SUBSCRIPTION: `/api/lawyer/subscription/current`,
    SUBSCRIPTIONS: `/api/lawyer/subscriptions`,
    SUBSCRIPTION_CHECKOUT: `/api/lawyer/subscription/checkout`,
    SUBSCRIPTION_SUCCESS: `/api/lawyer/subscription/success`,
    GET_REVIEWS: (id: string) => `/api/lawyer/review/${id}`,
    GET_CASES: '/api/lawyer/cases',
    GET_EARNINGS: '/api/lawyer/earnings',
    REQUEST_PAYOUT: '/api/lawyer/payout/request',
    PAYOUT_HISTORY: '/api/lawyer/payout/history',
    DASHBOARD_STATS: '/api/lawyer/dashboard/stats',
    SPECIALIZATIONS: '/api/lawyer/specializations'
  },
  CHAT: {
    CHECK_ACCESS: (lawyerId: string) => `/api/user/chat/access/${lawyerId}`,
    GET_ROOM: "/api/user/chat/room",
    GET_MESSAGES: (roomId: string) => `/api/user/chat/messages/${roomId}`,
    USER_ROOMS: "/api/user/chat/rooms",
    USER_LAWYER_ROOMS: (lawyerId: string) => `/api/user/chat/rooms/${lawyerId}`,
    LAWYER_ROOMS: "/api/lawyer/chat/rooms",
    LAWYER_USER_ROOMS: (userId: string) => `/api/lawyer/chat/rooms/${userId}`,
    LAWYER_MESSAGES: (roomId: string) => `/api/lawyer/chat/messages/${roomId}`,
    LAWYER_GET_ROOM: "/api/lawyer/chat/room",
    LAWYER_GET_ROOM_BY_ID: (roomId: string) => `/api/lawyer/chat/room/${roomId}`,
    GET_ROOM_BY_ID: (roomId: string) => `/api/user/chat/room/${roomId}`,
    UPLOAD_FILE: "/api/user/chat/upload",
    LAWYER_UPLOAD_FILE: "/api/lawyer/chat/upload",
    CAN_JOIN_CALL: (bookingId: string) => `/api/video-call/${bookingId}/can-join`,
    JOIN_CALL: (bookingId: string) => `/api/video-call/${bookingId}/join`
  },
  NOTIFICATION: {
    GET_USER: (userId: string) => `/api/user/notifications/${userId}`,
    GET_LAWYER: (userId: string) => `/api/lawyer/notifications/${userId}`,
    MARK_READ_USER: (id: string) => `/api/user/notifications/${id}/read`,
    MARK_READ_LAWYER: (id: string) => `/api/lawyer/notifications/${id}/read`,
  }
}

